### ISSUE TITLE
isc_list shortcode in Content breaks the block editor

### ISSUE THREAD

**Issue by webzunft** [webgilde/image-source-control#48]
New posts cannot be saved or existing ones auto-updated when the `[isc_list]` is used in the post content of the block editor. I added it using the `/shortcode` block and having images in the content as well. It doesn’t break all the time so I might be missing something.

At the same time, I can see a PHP issue raised in debug.log:

````
PHP Fatal error:  Uncaught Error: Maximum function nesting level of '256' reached, aborting! in /isc/wp-includes/class-wp-block-parser.php:83
Stack trace:
#0 /isc/wp-includes/class-wp-block-parser.php(477): WP_Block_Parser_Block->__construct(NULL, Array, Array, '\n\n', Array)
#1 /isc/wp-includes/class-wp-block-parser.php(548): WP_Block_Parser->freeform('\n\n')
#2 /isc/wp-includes/class-wp-block-parser.php(359): WP_Block_Parser->add_block_from_stack(456)
#3 /isc/wp-includes/class-wp-block-parser.php(236): WP_Block_Parser->proceed()
#4 /isc/wp-includes/blocks.php(521): WP_Block_Parser->parse('<!-- wp:paragra...')
#5 /isc/wp-includes/blocks.php(533): parse_blocks('<!-- wp:paragra...')
#6 /isc in /Users/thomas/Entwicklung/wp-testumgebungen/isc/wp-includes/class-wp-block-parser.php on line 83
````

Some tests I could do:

- unregister the shortcode
- log if the shortcode is actually interpreted while using the block editor

**Comment by webzunft** [comment]
The `[isc_list]` shortcode and so [this function](https://github.com/webgilde/image-source-control/blob/7d15a3f654a099202fdeb8b0c900dcb6221766d7/public/public.php#L296) does indeed run on autosave.

Removing the last line in the function helped, though that just confirms the issue is there, not how to resolve this.

I see two possible solutions:

- check if the shortcode accidentally creates an output instead of returning something as suggested [here](https://wordpress.stackexchange.com/questions/341770/shortcode-runs-when-editing-page)
- disable the shortcode for REST calls
